# Generated by Django 6.0.2 on 2026-02-18 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_attempts', models.PositiveIntegerField(default=0)),
                ('last_reminder_error', models.TextField(blank=True, null=True)),
                ('eskiz_request_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
